### ISSUE TITLE
Scrolling on phones does not work after editing a catch

### ISSUE THREAD

**Issue by crAZiAc** [crAZiAc/fokkersfishingblazor#4]
On phones, after editing a catch, scrolling does not work anymore

**Comment by crAZiAc** [comment]
Added this to app.css to fix this:

```css
body.mdc-dialog-scroll-lock {
    overflow: inherit;
}
```
